databases:
  - name: blog_db
    plan: free
    databaseName: blog_db
    user: blog_db

services:
  - type: web
    name: blog
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd blog_api && gunicorn blog_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: DATABASE_URL
        fromDatabase:
          name: blog_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
